# Generated by Django 3.0.2 on 2020-01-25 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import verification.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.CharField(default='none', max_length=30, primary_key=True, serialize=False)),
                ('original_image', models.ImageField(upload_to=verification.models.set_images_path)),
                ('result', models.BooleanField(blank=True, null=True)),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('chromosome_9', models.ImageField(blank=True, null=True, upload_to='')),
                ('chromosome_22', models.ImageField(blank=True, null=True, upload_to='')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verification.Case')),
                ('upload_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('case', 'id'),
            },
        ),
    ]
