# Generated by Django 3.0.2 on 2020-01-25 13:11

from django.db import migrations, models
import verification.models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='original_image',
            field=models.ImageField(upload_to=verification.models.ImagePath('original')),
        ),
    ]
